export { BREAKPOINTS } from "./BREAKPOINTS";
export { getLocalizedCatalogSection } from "./catalogSection";
export { CART_MIN_QUANTITY, WISHLIST_CLICK_DEBOUNCE_MS } from "./commerce";
export { getLocalizedFooter } from "./footer";
export * from "./headerActionsList";
export { getLocalizedHeroSlides } from "./heroSlides";
export { HOME_BANNER_FALLBACK } from "./homeBannerFallback";
export { MODALS } from "./modals";
export { getLocalizedNavigation } from "./navItems";
export { socialLinks } from "./socialLinks";
