# name: Telegram Push Notification

# on:
#   push:

# jobs:
#   notify:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Send Telegram message
#         run: |
#           TEXT="Новый push%0Aрепозиторий: ${{ github.repository }}%0AВетка: ${{ github.ref_name }}%0AАвтор: ${{ github.actor }}%0AКоммит: ${{ github.event.head_commit.message }}%0AСсылка: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"

#           curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
#             -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
#             -d "text=${TEXT}"

name: Notion Push Task for Merge to Dev

on:
  push:
    branches-ignore:
      - dev
      - main
      - master

jobs:
  create-notion-task:
    runs-on: ubuntu-latest

    steps:
      - name: Skip merge commits
        id: skip_check
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" == Merge\ * ]] || [[ "$COMMIT_MSG" == merge\ * ]]; then
            echo "is_merge=true" >> $GITHUB_OUTPUT
          else
            echo "is_merge=false" >> $GITHUB_OUTPUT
          fi
      - name: Create task in Notion
        if: steps.skip_check.outputs.is_merge == 'false'
        run: |
          TASK_TITLE="Замержить ветку \"${{ github.ref_name }}\" \"${{ github.actor }}\" на dev"
          ACTOR="${{ github.actor }}"
          PROJECT_ID="${{ vars.NOTION_PROJECT_PAGE_ID }}"
          DATABASE_ID="${{ secrets.NOTION_DATABASE_ID }}"
          PAYLOAD=$(jq -n \
            --arg database_id "$DATABASE_ID" \
            --arg task_title "$TASK_TITLE" \
            --arg actor "$ACTOR" \
            --arg project_id "$PROJECT_ID" \
            '{
              parent: {
                database_id: $database_id
              },
              properties: {
                "Задача": {
                  title: [
                    {
                      text: {
                        content: $task_title
                      }
                    }
                  ]
                },
                "Проект": {
                  relation: [
                    {
                      id: $project_id
                    }
                  ]
                },
                "Роль": {
                  select: {
                    name: "TeamLead"
                  }
                },
                "Поинт": {
                  select: {
                    name: "10 минут"
                  }
                }
              }
            }')
          echo "$PAYLOAD"
          RESPONSE=$(curl -s -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data "$PAYLOAD")
          echo "$RESPONSE"